openapi: 3.0.3
info:
  title: ''
  version: 1.0.0
paths:
  /api/claims/:
    get:
      operationId: api_claims_retrieve
      description: REST endpoints for viewing and submitting claims
      tags:
        - api
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Claim'
          description: ''
    post:
      operationId: api_claims_create
      description: REST endpoints for viewing and submitting claims
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Claim'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Claim'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Claim'
        required: true
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Claim'
          description: ''
  /api/claims/{id}:
    get:
      operationId: api_claim_detail
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this claim.
          schema:
            type: integer
      tags:
        - api
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Claim'
          description: ''
    put:
      operationId: api_claims_update
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this claim.
          schema:
            type: integer
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Claim'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Claim'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Claim'
        required: true
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Claim'
          description: ''
    patch:
      operationId: api_claims_partial_update
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this claim.
          schema:
            type: integer
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedClaim'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedClaim'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedClaim'
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Claim'
          description: ''
  /api/entities/:
    get:
      operationId: api_entities_retrieve
      description: REST endpoints for viewing and submitting entities
      tags:
        - api
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
          description: ''
    post:
      operationId: api_entities_create
      description: REST endpoints for viewing and submitting entities
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Entity'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Entity'
        required: true
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
          description: ''
  /api/entities/{id}:
    get:
      operationId: api_entity_detail
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this entity.
          schema:
            type: integer
      tags:
        - api
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
          description: ''
    put:
      operationId: api_entities_update
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this entity.
          schema:
            type: integer
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Entity'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Entity'
        required: true
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
          description: ''
    patch:
      operationId: api_entities_partial_update
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this entity.
          schema:
            type: integer
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedEntity'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedEntity'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedEntity'
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
          description: ''
  /api/evidence/:
    get:
      operationId: api_evidence_retrieve
      description: ''
      parameters:
        - in: query
          name: is_expert_verified
          schema:
            type: boolean
          description: Is this evidence expert verified?
      tags:
        - api
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Evidence'
          description: ''
    post:
      operationId: api_evidence_create
      description: ''
      parameters:
        - in: query
          name: is_expert_verified
          schema:
            type: boolean
          description: Is this evidence expert verified?
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Evidence'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Evidence'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Evidence'
        required: true
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Evidence'
          description: ''
  /api/evidence/{id}:
    get:
      operationId: api_evidence_detail
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this evidence.
          schema:
            type: integer
      tags:
        - api
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Evidence'
          description: ''
    put:
      operationId: api_evidence_update
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this evidence.
          schema:
            type: integer
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Evidence'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Evidence'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Evidence'
        required: true
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Evidence'
          description: ''
    patch:
      operationId: api_evidence_partial_update
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this evidence.
          schema:
            type: integer
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedEvidence'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedEvidence'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedEvidence'
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Evidence'
          description: ''
  /api/sources/:
    get:
      operationId: api_sources_retrieve
      description: REST endpoints for viewing and submitting sources
      tags:
        - api
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Source'
          description: ''
    post:
      operationId: api_sources_create
      description: REST endpoints for viewing and submitting sources
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Source'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Source'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Source'
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Source'
          description: ''
  /api/sources/{id}:
    get:
      operationId: api_source_detail
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this source.
          schema:
            type: integer
      tags:
        - api
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Source'
          description: ''
    put:
      operationId: api_sources_update
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this source.
          schema:
            type: integer
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Source'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Source'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Source'
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Source'
          description: ''
    patch:
      operationId: api_sources_partial_update
      description: ''
      parameters:
        - name: id
          in: path
          required: true
          description: A unique integer value identifying this source.
          schema:
            type: integer
      tags:
        - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedSource'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedSource'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedSource'
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Source'
          description: ''
components:
  schemas:
    Claim:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        claim_text:
          type: string
          maxLength: 200
        description:
          type: string
        topic:
          allOf:
            - $ref: '#/components/schemas/Topic'
          readOnly: true
        source_of_claim:
          type: integer
      required:
        - claim_text
        - id
        - source_of_claim
        - topic
    Entity:
      type: object
      properties:
        name:
          type: string
          maxLength: 100
        description:
          type: string
      required:
        - name
    Evidence:
      type: object
      properties:
        claim:
          allOf:
            - $ref: '#/components/schemas/Claim'
          readOnly: true
        source_of_evidence:
          allOf:
            - $ref: '#/components/schemas/Source'
          readOnly: true
        evidence_relationship:
          $ref: '#/components/schemas/EvidenceRelationshipEnum'
        description:
          type: string
        is_expert_verified:
          type: boolean
          readOnly: true
      required:
        - claim
        - evidence_relationship
        - is_expert_verified
        - source_of_evidence
    PatchedClaim:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        claim_text:
          type: string
          maxLength: 200
        description:
          type: string
        topic:
          allOf:
            - $ref: '#/components/schemas/Topic'
          readOnly: true
        source_of_claim:
          type: integer
    PatchedEntity:
      type: object
      properties:
        name:
          type: string
          maxLength: 100
        description:
          type: string
    PatchedEvidence:
      type: object
      properties:
        claim:
          allOf:
            - $ref: '#/components/schemas/Claim'
          readOnly: true
        source_of_evidence:
          allOf:
            - $ref: '#/components/schemas/Source'
          readOnly: true
        evidence_relationship:
          $ref: '#/components/schemas/EvidenceRelationshipEnum'
        description:
          type: string
        is_expert_verified:
          type: boolean
          readOnly: true
    PatchedSource:
      type: object
      properties:
        url:
          type: string
          format: uri
          maxLength: 200
        description:
          type: string
        source_degree:
          allOf:
            - $ref: '#/components/schemas/SourceDegreeEnum'
          nullable: true
        authors:
          type: array
          items:
            $ref: '#/components/schemas/Entity'
          readOnly: true
        date_retrieved:
          type: string
          format: date-time
          readOnly: true
    Source:
      type: object
      properties:
        url:
          type: string
          format: uri
          maxLength: 200
        description:
          type: string
        source_degree:
          allOf:
            - $ref: '#/components/schemas/SourceDegreeEnum'
          nullable: true
        authors:
          type: array
          items:
            $ref: '#/components/schemas/Entity'
          readOnly: true
        date_retrieved:
          type: string
          format: date-time
          readOnly: true
      required:
        - authors
        - date_retrieved
    Topic:
      type: object
      properties:
        name:
          type: string
          maxLength: 100
      required:
        - name
    EvidenceRelationshipEnum:
      enum:
        - PROVES
        - SUPPORTS
        - UNRELATED
        - INCONCLUSIVE
        - DISPUTES
        - DISPROVES
      type: string
    SourceDegreeEnum:
      enum:
        - ORIGINAL
        - PRIMARY
        - SECONDARY
        - TERTIARY
      type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: Session